webtalk_init -webtalk_dir D:/JaleedUSTP/RTL/RTLLab/week2/week2.sim/sim_1/behav/xsim/xsim.dir/tb_bcd_counter_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jun 28 22:43:32 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "83310e5e-64e0-4465-bf78-7d7acaf4bef5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "efb8064be6be4f03b2f6f7d3cabfa1a2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2419 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "210 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "11144_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3754256090 -regid "" -xml D:/JaleedUSTP/RTL/RTLLab/week2/week2.sim/sim_1/behav/xsim/xsim.dir/tb_bcd_counter_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/JaleedUSTP/RTL/RTLLab/week2/week2.sim/sim_1/behav/xsim/xsim.dir/tb_bcd_counter_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/JaleedUSTP/RTL/RTLLab/week2/week2.sim/sim_1/behav/xsim/xsim.dir/tb_bcd_counter_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
